version: '3.9'

services:
  de-pg-cr-af:
    image: sindb/de-pg-cr-af:latest
    ports:
      - 3000:3000
      - 3002:3002
      - 15432:5432
    volumes:
      - db_sp5:/var/lib/postgresql
      - ${AIRFLOW_DAGS_DIR:-./src/dags}:/lessons/dags

volumes:
  db_sp5:
